config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :users, only: [:show] do
   resources :avatars, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_one_attached :avatar
    has_many_attached :photo_sell
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController

    def create
        @user = User.find(params[:user_id])
        # ont attache au user l'avatar
        @user.avatar.attach() 
        redirect_to(user_path(@user))
      end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>Page Profil</h1>

<p>Bienvenue sur la page d'ajout d'un avatar pour le User portant l'id : <%=@user.id%></p>
<h3>Avatar actuel</h3>
<%if @user.avatar.attached?%>
  <%= image_tag @user.avatar %>
<%else%>
  <p>=== Il n'y a pas encore d'avatar lié à cet utilisateur ===</p>
<%end%>

<%= form_tag do %>
    
    <%= file_field_tag :avatar %>
    <%= submit_tag "uploader l'avatar" %>
  <% end %>
  
  <h3>Changer d'avatar ?</h3>
<%= form_tag user_avatars_path(@user), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>